cppfilelist = {'TIFFloadFrame_16bit_CPU.cpp', ...
    'CreateSubImages.cpp', ...
    'det_DWT_newconv2_threshold.cpp',...
    'det_DWT_Findparticles_float.cpp', ...
    'PostProcessingFittingData.cpp', ...
    'LinkPoints.cpp', ...
    'PostProcessLinkData.cpp', ...
    };

for m =1:length(cppfilelist)
    tfile = cppfilelist{m};
    disp(['compile file: ' tfile]);
    T = evalc(['mex ' tfile]);
end

disp('compile done.');